version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.13.1
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - endpoints:/etc/prometheus/targets/
    ports:
      - 9090:9090

  target:
    image: nginx
    restart: always
    volumes:
      - ./nginx/content/:/etc/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:9090
    environment:
      - NGINX_PORT=9090
    labels:
      prometheus.nginx.enabled: "true"
      prometheus.nginx.target.port: "9090"
      prometheus.nginx.target.path: "/metrics"
      prometheus.nginx.target.interval: "15s"
      prometheus.nginx.label.source: "docker"

volumes:
  endpoints:
