version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.13.1
    volumes:
      - ./prometheus/:/etc/prometheus/
#      - prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#    restart: always

  web:
    image: nginx
    volumes:
      - ./nginx/content/:/etc/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    labels:
      prometheus.docker.nginx.enabled: "true"
      prometheus.docker.nginx.target.port: "6060"
      prometheus.docker.nginx.target.path: "/metrics"
      prometheus.docker.nginx.target.interval: "15s"
      prometheus.docker.nginx.label.source: "docker"

#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

#  docker-discovery:
#    build: ../build/Dockerfile


#volumes:
#  logvolume01: {}
