version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.13.1
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - endpoints:/etc/prometheus/targets/
    ports:
      - 9090:9090
    labels:
      prometheus.target.enabled: "true"
      prometheus.target.job: "prometheus"
      prometheus.target.port: "9090"
      prometheus.target.path: "/metrics"
      prometheus.target.label.source: "docker"

  target:
    image: nginx
    restart: always
    volumes:
      - ./nginx/content/:/etc/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:9090
    environment:
      - NGINX_PORT=9090
    labels:
      prometheus.target.enabled: "true"
      prometheus.target.job: "nginx"
      prometheus.target.port: "9090"
      prometheus.target.path: "/metrics"
      prometheus.target.label.source: "docker"

  discovery:
    build:
      context: ../
      dockerfile: build/Dockerfile
#    restart: always
    volumes:
      - endpoints:/etc/prometheus/targets/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      prometheus.discovery.scrapeInterval: "15s"
      prometheus.discovery.refreshInterval: "30m"
      prometheus.discovery.logLevel: "debug"
      prometheus.discovery.label.source: "docker"

volumes:
  endpoints:
